### ISSUE TITLE
invalid %N$ use detected on NixOS

### ISSUE THREAD

**Issue by lepz0r** [RiedleroD/nosefart#2]
I compiled this on NixOS but I got `invalid %N$ use detected` before the music is started

**Comment by RiedleroD** [comment]
huh, somehow github never notified me of this issue. Will take a look at it later this week, hopefully with the help of someone using nix

**Comment by aprilthepink** [comment]
Its nixing time

**Comment by aprilthepink** [comment]
@lepz0r https://github.com/RiedleroD/nosefart/pull/4

**Comment by aprilthepink** [comment]
also the compile error getting fixed rn

**Comment by RiedleroD** [comment]
@lepz0r it should be fixed now, please reopen the issue if it isn't ^^
